// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/NuriCareers/Sreekanth-Cheriyanath-coding-challenge/blockinfo/domain"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetBlockInfo provides a mock function with given fields: _a0
func (_m *Service) GetBlockInfo(_a0 *domain.Request) (*domain.Block, error) {
	ret := _m.Called(_a0)

	var r0 *domain.Block
	if rf, ok := ret.Get(0).(func(*domain.Request) *domain.Block); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Block)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.Request) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTranInfo provides a mock function with given fields: _a0
func (_m *Service) GetTranInfo(_a0 *domain.Request) (*domain.Transaction, error) {
	ret := _m.Called(_a0)

	var r0 *domain.Transaction
	if rf, ok := ret.Get(0).(func(*domain.Request) *domain.Transaction); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.Request) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
